[env:esp32-s3-supermini]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200

; Настройки памяти под плату SuperMini 4MB Flash / 2MB PSRAM
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.partitions = partitions_singleapp.csv

; Включаем встроенный USB для логов и поддержку встроенной PSRAM
build_flags =
    -D CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG=1
    -D CONFIG_SPIRAM=1
    -D CONFIG_SPIRAM_BOOT_INIT=1
    -D CONFIG_SPIRAM_MODE_QUAD=1
